"""dropped the picture column from user

Revision ID: 2000a7dbc097
Revises: 8150fd6a2f83
Create Date: 2026-01-11 00:02:58.482031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2000a7dbc097'
down_revision: Union[str, Sequence[str], None] = '8150fd6a2f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
